model-trained:
  feature: false
  station: false
optimized: true
params:
  colsample_bytree: 0.5548607536901364
  device: cuda
  learning_rate: 0.02477745750063519
  max_depth: 3
  n_estimators: 3333
  random_state: 42
  reg_lambda: 0.41429502108471966
  subsample: 0.9478516285443115
params_grid:
  colsample_bytree:
  - 0.5
  - 1.0
  learning_rate:
  - 0.0001
  - 0.1
  max_depth:
  - 3
  - 10
  n_estimators:
  - 500
  - 5000
  reg_lambda:
  - 0.01
  - 10.0
  subsample:
  - 0.5
  - 1.0
